"""Pydantic schemas package."""

from app.schemas.pothole import (
    BoundingBoxSchema,
    PotholeBase,
    PotholeCreate,
    PotholeUpdate,
    PotholeResponse,
    PotholeListResponse,
    PotholeStatusHistoryResponse,
    PotholeStatusUpdateRequest,
    Phase1GPSCoordinate,
    Phase1DetectionItem,
    Phase1IngestRequest,
    Phase1IngestResponse,
    PotholeStatsResponse,
    ReportCreateRequest,
    PotholeReportResponse,
    CivicAuthorityResponse,
    BatchReportResponse,
)

__all__ = [
    "BoundingBoxSchema",
    "PotholeBase",
    "PotholeCreate",
    "PotholeUpdate",
    "PotholeResponse",
    "PotholeListResponse",
    "PotholeStatusHistoryResponse",
    "PotholeStatusUpdateRequest",
    "Phase1GPSCoordinate",
    "Phase1DetectionItem",
    "Phase1IngestRequest",
    "Phase1IngestResponse",
    "PotholeStatsResponse",
    "ReportCreateRequest",
    "PotholeReportResponse",
    "CivicAuthorityResponse",
    "BatchReportResponse",
]
